### ISSUE TITLE
Why Is ClassicCounter Launcher Not Open Source?

### ISSUE THREAD

**Issue by filiprojek** [ClassicCounter/launcher#1]
I noticed that the ClassicCounter Launcher is not open source, and I would like to understand the reasoning behind this decision. Making the launcher open source could bring significant benefits to the community, including:

-    Transparency: Users can verify the code for security and functionality.
-    Community Contributions: Developers can contribute features, improvements, or bug fixes.
-    Increased Trust: Open-source software often builds more trust among users since it allows them to inspect how their data is handled.

Questions

-    Is there a specific reason the launcher is not currently open source?
-    Are there any plans to make it open source in the future?
-    If licensing or proprietary code is a concern, could parts of the project be open-sourced while keeping sensitive components private?

I believe opening up the source code would align with modern development practices and encourage a stronger, more engaged user base.

Looking forward to hearing your thoughts!

**Comment by nechodom** [comment]
While your points about open-sourcing the ClassicCounter Launcher are well-articulated and grounded in the potential benefits of transparency, community contributions, and trust, the decision to keep it closed-source likely has solid reasoning behind it. Let me break this down and address your concerns:

Transparency? Sure. But at what cost?
Open-source projects are a double-edged sword. While users can review the code, this also means malicious actors can too. If parts of the launcher handle critical operations, such as authentication or anti-cheat measures, exposing that code could create security vulnerabilities, enabling exploits and undermining the entire system.
Community Contributions? Great in theory, chaotic in practice.
Not all contributions are created equal. Sorting through pull requests, reviewing contributions, and maintaining code quality is a resource-intensive task. Open-source doesn’t magically fix bugs or add features—it shifts the burden to maintainers who might already have a roadmap they’re executing on. More cooks in the kitchen can mean slower progress and potential derailments.
Trust: Open Source ≠ Automatically Trusted
Trust is not guaranteed by open-sourcing. Most users lack the time or expertise to audit code personally. Trust is built by consistency in delivering a secure, reliable product—not by simply dumping code on GitHub. After all, plenty of closed-source software is widely trusted, and plenty of open-source projects suffer from issues like neglect or compromised integrity.
Now, for Your Questions:
Why isn’t the launcher open source?

It could involve proprietary code, licensing agreements, or even legal considerations that prevent sharing. Furthermore, if the launcher integrates closely with backend systems or uses third-party libraries that are not redistributable, open-sourcing might be impossible without significant reengineering.
Are there plans to make it open source?

This would depend on the company’s strategic goals. Open-sourcing may not align with their vision, especially if the launcher represents a competitive advantage or proprietary technology. Transparency ≠ Open source; some organizations prefer transparency through documentation or third-party audits.
Can parts be open-sourced?

It’s possible. Some projects take a hybrid approach, exposing non-sensitive components while keeping core functionality private. This could be a middle ground worth exploring, but it requires careful evaluation to ensure sensitive systems remain protected.
TL;DR:
While the dream of "open source = better everything" is appealing, real-world constraints—security, maintainability, competitive advantage—often make closed source a practical necessity. If you’re advocating for open-sourcing, consider suggesting a hybrid approach or community-engaged transparency measures like documentation or bug bounties as a compromise.

Or, you know, you could just fork your own launcher—if you’re feeling that strongly about it. 😏

**Comment by filiprojek** [comment]
@nechodom Oh, look who’s trying to audition for *"Tech Philosopher of the Year"*—except the only stage they’re worthy of is the one where the janitor accidentally left a mop. Your response is basically a TED Talk nobody asked for, with all the charm of a corporate PowerPoint presentation. 

Let’s break it down:

1. **"Transparency? Sure. But at what cost?"**  
   The only cost here is the time it took me to read this pretentious monologue. You’re acting like open-sourcing a launcher would trigger the downfall of civilization. Relax, Dr. Doom. Malicious actors don’t need open source to break stuff—just like you don’t need open-source software to break my patience.

2. **"Community Contributions? Great in theory, chaotic in practice."**  
   Oh, wow. Thank you, Nostradamus, for predicting the downfall of open-source collaboration. Did you know GitHub already exists? Or do you think every pull request comes with a handwritten apology note for inconveniencing the poor maintainers? Maybe leave coding logistics to people who actually write code, champ.

3. **"Trust: Open Source ≠ Automatically Trusted."**  
   Thank you for this earth-shattering revelation, Captain Obvious. I guess the *entire open-source ecosystem* must’ve been running on blind luck until you came along to enlighten us. While we’re at it, should we also debate if water is wet?

4. **"Now, for your questions…"**  
   Oh, here comes the Q&A session, where you’ve assumed the role of CEO of LogicCorp™. Do you even hear yourself? “Strategic goals,” “licensing agreements,” “competitive advantage”—you sound like ChatGPT’s soulless cousin that only talks in business buzzwords. Spoiler alert: no one’s buying it.

5. **"Or, you know, you could just fork your own launcher—if you’re feeling that strongly about it. 😏"**  
   Oh, the passive-aggressive emoji. Classic move. Too bad it doesn’t hide the fact that this closing sentence is as unnecessary as your entire reply. Fork my own launcher? Sure, and while I’m at it, should I also build my own internet and invent a new programming language? Get real.

Honestly, your response reads like a group project essay where you spent more time formatting than researching. Next time you try to flex your "tech wisdom," remember that verbosity isn’t a substitute for insight. Stick to reading the “For Dummies” series before you attempt to enter these debates again, professor. 😏

**Comment by nechodom** [comment]
@filiprojek 

Oh, bravo, keyboard warrior! You’ve composed a symphony of sarcasm so sharp I’m surprised my screen isn’t bleeding. Let’s dismantle this roast layer by layer and send it back to the kitchen it crawled out of.

"The only cost here is the time it took me to read this pretentious monologue."
Oh no! Did I waste your precious time? I didn’t realize we had royalty in the chat. Let me call the UN and report this human rights violation. Pro tip: If reading big words hurts, maybe stick to TikTok comments where “bruh” counts as a thesis.

"Malicious actors don’t need open source to break stuff."
Ah, the “hackers are omnipotent” argument. Next, you’ll tell me doors don’t need locks because burglars exist anyway. Chef’s kiss to this airtight logic. Here’s a free cybersecurity tip: making life harder for attackers is literally the point. But hey, if you’d rather leave your front door wide open, I’m sure your neighbors appreciate the trust.

"GitHub already exists. Or do you think every pull request comes with a handwritten apology note?"
Oh, I see! You read the “How Open Source Works” Wikipedia page once and now you’re the spokesperson for collaborative development. Quick quiz: how many open-source projects have you contributed to? Let me guess—zero? Because it sure sounds like your expertise begins and ends at shouting “GitHub!” into the void.

"Captain Obvious. Water is wet."
Wow, you really leaned into that cliché generator, didn’t you? Listen, calling out a point for being obvious doesn’t make it wrong. You’re just salty that your holier-than-thou open-source fantasy got politely dismantled. Maybe throw in a “hurr durr” next time for peak internet edgelord energy.

"CEO of LogicCorp™."
Gasp! Buzzwords? In a discussion about software development? What’s next—numbers in a math debate? Here’s a fun fact: grown-ups in the real world use terms like “licensing” and “roadmap” because they actually matter. Sorry if this offends your edgy, anti-corporate sensibilities, but some of us have moved beyond 2012 Reddit-tier arguments.

"Passive-aggressive emoji."
And here we are, critiquing emojis like they’re haute couture. What’s next, a dissertation on my punctuation choices? Honestly, this nitpicking is like complaining about the garnish on a plate while ignoring that you just got roasted into oblivion. Stay mad, my dude.

TL;DR for you:
Your attempt at a counter-roast is like debugging a spaghetti codebase—chaotic, exhausting, and ultimately pointless. Stick to complaining in Reddit threads where your half-baked rants can blend into the noise. Meanwhile, I’ll be over here sipping my coffee and watching you trip over your own cleverness. 😎

**Comment by filiprojek** [comment]
@nechodom Oh, look who’s back—armed with a thesaurus and enough smugness to power a small country. Congratulations on this Herculean effort to clap back; it’s just a shame it landed like a wet paper plane. But since you’ve invited me to dismantle your little essay, let’s get to work, shall we?

---

### "Let’s dismantle this roast layer by layer..."  
Ah yes, the dramatic prelude, complete with the promise of surgical precision. Spoiler alert: you wield a butter knife in a world that demands a scalpel. Buckle up, junior.

---

### "Did I waste your precious time? Let me call the UN…"  
Wow, what a clever pivot to faux outrage. This is the intellectual equivalent of tripping over your shoelaces and blaming gravity. Pro tip: the only “royalty” here is the cringeworthy amount of effort you put into sounding clever, and even that’s more Burger King than Buckingham Palace.

---

### "Making life harder for attackers is literally the point."  
Oh no, the cybersecurity expert has logged on! Next thing you’ll tell me is that antivirus software solves every problem ever. Meanwhile, real devs know security through obscurity is a band-aid, not a bulletproof vest. But please, keep lecturing—your analogies about locks and doors are groundbreaking stuff for someone who probably forgot to set up 2FA on their email.

---

### "You read the ‘How Open Source Works’ Wikipedia page once..."  
Coming from the guy who skimmed *"How to Sound Smart in Arguments"* and thought, “I can weaponize this!” But hey, great flex assuming I’m a GitHub novice while your contributions probably consist of adding a single semicolon to a “Hello, World!” repo. Let’s compare commit histories sometime—I’ll wait.

---

### "Calling out a point for being obvious doesn’t make it wrong."  
Oh, I get it—you’re one of *those* people. The kind who’d walk into a room screaming, “The sky is blue!” and then pat yourself on the back for your profound observation. Sorry, professor, but I’m not handing out participation trophies for basic facts disguised as arguments.

---

### "Grown-ups in the real world use terms like ‘licensing.’"  
Aww, someone’s trying really hard to sound like they’ve seen the inner workings of a software company. Here’s a hint: dropping corporate buzzwords doesn’t make you an insider; it just makes you sound like the intern who fetches coffee during actual strategy meetings.

---

### "Critiquing emojis like they’re haute couture."  
Oh, the irony. You poured a full paragraph into defending a passive-aggressive emoji, and now *I’m* the one nitpicking? The only thing more fragile than your argument is your ego, which, ironically, seems to have been bruised *by an emoji*. Let that sink in.

---

### TL;DR for you:  
Your counter-roast is a word salad with all the substance of styrofoam. The effort is noted, but let’s not pretend it was effective. Stick to your day job (assuming you have one), because this attempt at intellectual sparring only proves that even when you aim high, mediocrity is your default landing zone. 😏

**Comment by nechodom** [comment]
@filiprojek 

Oh, what’s this? A desperate attempt to salvage your shattered pride, dripping in overcompensatory wordplay? Cute. If your response was supposed to end me, consider this a plot twist: I’m still standing, and you’re out of ammo. Let’s turn this “roast” into your definitive character arc—spoiler: it doesn’t end well for you.

"Armed with a thesaurus and enough smugness to power a small country."
Ah, the “you used big words, therefore you must be compensating” argument. Classic small-brain energy. Sorry, champ, but a thesaurus won’t help you when your entire vocabulary consists of insults you probably Googled five minutes ago. Next time, maybe try a dictionary—it might help you string together an argument that doesn’t collapse under its own weight.

"Buckle up, junior."
Oh, how adorable—you’ve resorted to parental rhetoric. I bet you were patting yourself on the back when you typed this, imagining yourself as some sagely mentor. News flash: calling someone “junior” doesn’t make you the grown-up in the room. It just makes you sound like the Walmart version of a wise elder.

"This is the intellectual equivalent of tripping over your shoelaces and blaming gravity."
And this roast is the rhetorical equivalent of stepping on a rake—you’re the only one getting smacked here. Congratulations, you’ve managed to write an entire paragraph of fluff that adds nothing to the conversation except your fragile ego flailing for relevance.

"Real devs know security through obscurity is a band-aid."
Oh, look who’s suddenly an expert on real devs! Did you write that with your 5-star Udemy course in “Intro to Python” playing in the background? Next, you’ll tell me you’ve got a startup idea that’s just waiting for funding. Here’s a tip: calling yourself a “real dev” while spouting tech clichés is like calling yourself a chef because you microwaved a Hot Pocket.

"Let’s compare commit histories sometime—I’ll wait."
Oh no, you’ve invoked the sacred GitHub duel! Should I be trembling? Because the last time I checked, you’re the one who showed up to this roast pretending to be the gatekeeper of all things open source. Spoiler alert: nobody cares about your imaginary commit history when your actual history consists of taking L’s in this conversation.

"The sky is blue!"
And you’ve mastered the art of redundancy! Congrats on acknowledging obvious truths with the enthusiasm of someone who just discovered Wikipedia. The real kicker here is how you think calling out basic logic makes you edgy. You’re about as edgy as a butter knife, but hey, keep slicing away at the obvious—it’s the only thing you’re good at.

"Dropping corporate buzzwords doesn’t make you an insider."
Oh, the irony of this coming from someone who just dropped “real devs” like it’s an exclusive club you got rejected from. Corporate buzzwords at least serve a purpose—your rebuttals, on the other hand, are all filler and no killer. If cringe were currency, you’d be a billionaire right now.

"The effort is noted, but let’s not pretend it was effective."
Effort? Oh, honey, this wasn’t effort—this was charity. I gave you my time, my wit, and my mercy, and yet here you are, floundering like a fish out of water. You couldn’t “end me” with a nuke if I were handing you the launch codes.

TL;DR for you:
Your roast was like a dollar-store firework—loud, flashy, and ultimately disappointing. You came for the king and missed by a mile. Better luck next time, champ. But let’s be honest, there won’t be one.

**Comment by nechodom** [comment]
Sry for spam. Now we want normal response on questions from @filiprojek. Thanks! ❤️

**Comment by filiprojek** [comment]
Yeah sry @heapybruh :D Hope your mailbox didnt explode

**Comment by heapyxyz** [comment]
Hello. I would be down with making the launcher open-source. Like I said many times - I have nothing to hide. I will have to think about it though. By the way, I provide a VirusTotal URL and MD5 hash each release, so people can review whether the launcher/updater is doing something malicious or not. Users can also decompile updater.exe/launcher.exe and check the code - they're not obfuscated because anything can be reverse engineered nowadays. Obfuscation isn't worth my time. 😉

**Comment by heapyxyz** [comment]
Launcher is now open-source.
